[package]
org = "ballerinax"
name = "snowflake"
version = "1.2.0"
authors = ["Ballerina"]
keywords = ["IT Operations/Cloud Services", "Cost/Paid"]
repository = "https://github.com/ballerina-platform/module-ballerinax-snowflake"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[[platform.java11.dependency]]
path = "../native/build/libs/snowflake-native-1.2.0.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.10.0.jar"
